export enum CurtainMaterial {
  COTTON = "COTTON",
  POLYESTER = "POLYESTER",
  SILK = "SILK",
  LINEN = "LINEN",
  VELVET = "VELVET",
  WOOL = "WOOL",
  SYNTHETIC_BLEND = "SYNTHETIC_BLEND",
  LACE = "LACE",
  ACRYLIC = "ACRYLIC",
  MICROFIBER = "MICROFIBER",
}
